/*******************************************************************************
* Copyright 2008-2009, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

// This file is present to mark that the
// component has a verilog implementation

// The verilog code is generated by the
// verilog customization hook depending on
// the parameters