/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ezi2c.h"
#include "ezi2c_PINS.h"
#include "ezi2c_PVT.h"
#include "ezi2c_EZI2C.h"
#include "ezi2c_EZI2C_PVT.h"
#include "ezi2c_BOOT.h"
#include "adc.h"
#include "pressure.h"
#include "pressure_aliases.h"
#include "clockled.h"
#include "BLUELED.h"
#include "BLUELED_aliases.h"
#include "Bootloadable.h"
#include "REDLED.h"
#include "REDLED_aliases.h"
#include "V036.h"
#include "V036_aliases.h"
#include "ezi2c_SCBCLK.h"
#include "ezi2c_sda.h"
#include "ezi2c_sda_aliases.h"
#include "ezi2c_scl.h"
#include "ezi2c_scl_aliases.h"
#include "ezi2c_SCB_IRQ.h"
#include "adc_IRQ.h"
#include "adc_intClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

