/*******************************************************************************
* Copyright 2008-2009, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cypress.Comps.PinsAndPorts.cy_pins_v1_10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cypress.Comps.PinsAndPorts.cy_pins_v1_10.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All Pins].
        /// </summary>
        internal static string AllPins {
            get {
                return ResourceManager.GetString("AllPins", resourceCulture);
            }
        }
        
        internal static byte[] AnalogEMF {
            get {
                object obj = ResourceManager.GetObject("AnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BidirEMF {
            get {
                object obj = ResourceManager.GetObject("BidirEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; passed to the function &apos;{1}&apos; contains the following error: &apos;{2}&apos;..
        /// </summary>
        internal static string CustFunctError {
            get {
                return ResourceManager.GetString("CustFunctError", resourceCulture);
            }
        }
        
        internal static byte[] DefaultDriveModesEMF {
            get {
                object obj = ResourceManager.GetObject("DefaultDriveModesEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteImage {
            get {
                object obj = ResourceManager.GetObject("DeleteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DigInAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("DigInAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigInEMF {
            get {
                object obj = ResourceManager.GetObject("DigInEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigInNCAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("DigInNCAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigInNCEMF {
            get {
                object obj = ResourceManager.GetObject("DigInNCEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigOutEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigOutNCEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutNCEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigOutNCOEEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutNCOEEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DigOutOEEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutOEEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias names cannot be repeated. &apos;{0}&apos; has been used {1} times..
        /// </summary>
        internal static string Err_AliasRepeated {
            get {
                return ResourceManager.GetString("Err_AliasRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Invalid number of characters entered; all entries must contain {1} characters. &apos;{2}&apos; is {3} characters long..
        /// </summary>
        internal static string Err_BitVectorValueIncorrectLength {
            get {
                return ResourceManager.GetString("Err_BitVectorValueIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; is not a valid option..
        /// </summary>
        internal static string Err_BitVectorValueInvalidOption {
            get {
                return ResourceManager.GetString("Err_BitVectorValueInvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Invalid character found. Valid values must only contain 0&apos;s and 1&apos;s. &apos;{1}&apos; is not a valid character..
        /// </summary>
        internal static string Err_BitVectorValueOnlyOnesAndZeros {
            get {
                return ResourceManager.GetString("Err_BitVectorValueOnlyOnesAndZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: The component cannot use analog if it is set to be Contiguous (and the number of pins is greater than one), either remove the use of analog from the &apos;Pins/Type&apos; tab or remove the Contiguous restriction on the &apos;Mapping&apos; tab..
        /// </summary>
        internal static string Err_CannotBeContiguousAndAnalog {
            get {
                return ResourceManager.GetString("Err_CannotBeContiguousAndAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Cannot enable the input buffer with a drive mode of Analog High-Z..
        /// </summary>
        internal static string Err_CannotEnableIBufAndAnalogHiZ {
            get {
                return ResourceManager.GetString("Err_CannotEnableIBufAndAnalogHiZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: SIO features have been used by this pin therefore analog cannot be used. (SIO features include: HotSwap set to true, ThresholdLevels set to anything but LVTTL or CMOS, OutputDriveLevel set to Vref, and/or DriveCurrents set to a 25mA sink).
        /// </summary>
        internal static string Err_CannotUseAnalogAndSIO {
            get {
                return ResourceManager.GetString("Err_CannotUseAnalogAndSIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: SIO features have been used by this pin therefore LVTTL cannot be used for its threshold level. (SIO features include: HotSwap set to true, ThresholdLevels set to anything but LVTTL or CMOS, OutputDriveLevel set to Vref, and/or DriveCurrents set to a 25mA sink).
        /// </summary>
        internal static string Err_CannotUseLVTTLAndSIO {
            get {
                return ResourceManager.GetString("Err_CannotUseLVTTLAndSIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; contains more precision than is supported. Only one decimal place of precision is supported..
        /// </summary>
        internal static string Err_InvalidIOVoltagePercision {
            get {
                return ResourceManager.GetString("Err_InvalidIOVoltagePercision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; is not in a valid number format..
        /// </summary>
        internal static string Err_InvalidNumFormat {
            get {
                return ResourceManager.GetString("Err_InvalidNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; is not between the legal range of 1.7 volts to 5.5 volts..
        /// </summary>
        internal static string Err_NotInIOVoltageRange {
            get {
                return ResourceManager.GetString("Err_NotInIOVoltageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; is not a valid alias. An alias must be a valid C/C++ identifier name. {2}.
        /// </summary>
        internal static string Err_NotValidCIdentifier {
            get {
                return ResourceManager.GetString("Err_NotValidCIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When SIO&apos;s are paired their Input Thresholds must match..
        /// </summary>
        internal static string Err_SIOPairInputsDontMatch {
            get {
                return ResourceManager.GetString("Err_SIOPairInputsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When SIO&apos;s are paired their Output Drive Levels must match..
        /// </summary>
        internal static string Err_SIOPairOutputsDontMatch {
            get {
                return ResourceManager.GetString("Err_SIOPairOutputsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be contiguous and have more than 2 single SIO pins in a row. Making them contiguous means they will have to share an SIO pair on the device. Either group the single SIO pins or change the LayoutMode to remove the contiguous restriction..
        /// </summary>
        internal static string Err_TooManySingleSIOInARow {
            get {
                return ResourceManager.GetString("Err_TooManySingleSIOInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration will not be place able. Cannot have two single SIO pins next to an SIO pair if the component is set to be contiguous. Either remove the contiguous constraint or group the single SIO pins..
        /// </summary>
        internal static string Err_TooManySingleSIONextToSIOPair {
            get {
                return ResourceManager.GetString("Err_TooManySingleSIONextToSIOPair", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] HiImpedanceAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("HiImpedanceAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HiImpedanceDigitalEMF {
            get {
                object obj = ResourceManager.GetObject("HiImpedanceDigitalEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Indeterminate&gt;.
        /// </summary>
        internal static string Indeterminate {
            get {
                return ResourceManager.GetString("Indeterminate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MoveDownImage {
            get {
                object obj = ResourceManager.GetObject("MoveDownImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveUpImage {
            get {
                object obj = ResourceManager.GetObject("MoveUpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] OpenDrainDrivesHighEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesHighEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OpenDrainDrivesLowEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesLowEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PairSIOsImage {
            get {
                object obj = ResourceManager.GetObject("PairSIOsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (two arguments are expected: `=CalculateSIOGroupCount($sio_info, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CalculateSIOGroupCount {
            get {
                return ResourceManager.GetString("ParamCntErr_CalculateSIOGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateCSVFromBitVector(bitVectorParamName, bitVectorString, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateCSVFromBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateCSVFromBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateCSVFromInputOnlyBitVector(bitVectorParamName, bitVectorString, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateCSVFromInputOnlyBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateCSVFromInputOnlyBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateCSVFromOutputOnlyBitVector(bitVectorParamName, bitVectorString, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateCSVFromOutputOnlyBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateCSVFromOutputOnlyBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateDriveModesCSV($DriveModes, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateDriveModesCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateDriveModesCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos;(four arguments are expected: `=CreateHysteresisCSV($ThresholdLevels, $sio_info, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateHysteresisCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateHysteresisCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateInitialDriveStatesCSV($InitialDriveStates, $DriveModes, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateInitialDriveStatesCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateInitialDriveStatesCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (three arguments are expected: `=CreateInputBufferBitVector($ThresholdLevels, $sio_info, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateInputBufferBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateInputBufferBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateInputBufferesEnabledCSV($InputBuffersEnabled, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateInputBufferesEnabledCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateInputBufferesEnabledCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreateIOVoltagesCSV($IOVoltages, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreateIOVoltagesCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateIOVoltagesCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (four arguments are expected: `=CreateOutputBufferBitVector($OutputDriveLevels, $sio_info, $PinTypes, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CreateOutputBufferBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateOutputBufferBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (expected `=CreatePinAliasesCSV($PinAliases, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreatePinAliasesCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreatePinAliasesCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (two arguments is expected: `=CreatePinModeString($PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_CreatePinModeString {
            get {
                return ResourceManager.GetString("ParamCntErr_CreatePinModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (seven arguments are expected: `=CreateSIOInfoCSV($SIOGroups, $HotSwaps, $ThresholdLevels, $OutputDriveLevels, $DriveCurrents, $PinTypes, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CreateSIOInfoCVS {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateSIOInfoCVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (five arguments are expected: `=CreateSIORefSelBitVector($OutputDriveLevels, $ThresholdLevels, $sio_info, $PinTypes, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CreateSIORefSelCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateSIORefSelCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (four arguments are expected: `=CreateSIOVTripBitVector($ThresholdLevels, $sio_info, $PinTypes, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CreateSIOVTripBitVector {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateSIOVTripBitVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (three arguments are expected: `=CreateVTripCSV($ThresholdLevels, $PinTypes, $width)`)..
        /// </summary>
        internal static string ParamCntErr_CreateVTripCSV {
            get {
                return ResourceManager.GetString("ParamCntErr_CreateVTripCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (five arguments are expected: `=IsHomogeneous($PinTypes, $sio_info, $sio_refsel, $NumPins, $sio_group_cnt)`)..
        /// </summary>
        internal static string ParamCntErr_IsHomogeneous {
            get {
                return ResourceManager.GetString("ParamCntErr_IsHomogeneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments to call function &apos;{0}&apos; (three arguments are expected: `=UsesInterrupts($InterruptModes, $PinTypes, $NumPins)`)..
        /// </summary>
        internal static string ParamCntErr_UsesInterrupts {
            get {
                return ResourceManager.GetString("ParamCntErr_UsesInterrupts", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PinAliasImage {
            get {
                object obj = ResourceManager.GetObject("PinAliasImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PinImage {
            get {
                object obj = ResourceManager.GetObject("PinImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ResPullDownEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullDownEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ResPullUpDownEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpDownEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ResPullUpEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIO Pair.
        /// </summary>
        internal static string SIOPair {
            get {
                return ResourceManager.GetString("SIOPair", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SIOPinImage {
            get {
                object obj = ResourceManager.GetObject("SIOPinImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] StrongDriveEMF {
            get {
                object obj = ResourceManager.GetObject("StrongDriveEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated terminal not found..
        /// </summary>
        internal static string TermNotFound {
            get {
                return ResourceManager.GetString("TermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled bit vector param type &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledBitVectorParamType {
            get {
                return ResourceManager.GetString("UnhandledBitVectorParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled drive mode &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledDriveMode {
            get {
                return ResourceManager.GetString("UnhandledDriveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled input only bit vector param type &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledInputOnlyBitVectorParamType {
            get {
                return ResourceManager.GetString("UnhandledInputOnlyBitVectorParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled layout mode &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledLayoutMode {
            get {
                return ResourceManager.GetString("UnhandledLayoutMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled output only bit vector param type &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledOutputBitVectorParamType {
            get {
                return ResourceManager.GetString("UnhandledOutputBitVectorParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled output drive level type &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledOutputDriveLevel {
            get {
                return ResourceManager.GetString("UnhandledOutputDriveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled param name &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledParamName {
            get {
                return ResourceManager.GetString("UnhandledParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled pin type &apos;{0}&apos;.
        /// </summary>
        internal static string UnhandledPinType {
            get {
                return ResourceManager.GetString("UnhandledPinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled SIO group value &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledSIOGroup {
            get {
                return ResourceManager.GetString("UnhandledSIOGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled sio info &apos;{0}&apos;.
        /// </summary>
        internal static string UnhandledSIOInfo {
            get {
                return ResourceManager.GetString("UnhandledSIOInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled sio ref sel value &apos;{0}&apos;.
        /// </summary>
        internal static string UnhandledSIORefSel {
            get {
                return ResourceManager.GetString("UnhandledSIORefSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled threshold level &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledThreshold {
            get {
                return ResourceManager.GetString("UnhandledThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownParam {
            get {
                return ResourceManager.GetString("UnknownParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown terminal name &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownTerm {
            get {
                return ResourceManager.GetString("UnknownTerm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnpairSIOsImage {
            get {
                object obj = ResourceManager.GetObject("UnpairSIOsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
