//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZI2C_v1_60 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZI2C_v1_60.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Configuration.
        /// </summary>
        internal static string BasicTabCaption {
            get {
                return ResourceManager.GetString("BasicTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabCaption {
            get {
                return ResourceManager.GetString("BuiltInTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rate must be between 50 kbps and 1 Mbps..
        /// </summary>
        internal static string BusSpeedEP {
            get {
                return ResourceManager.GetString("BusSpeedEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the &quot;Pin connections&quot; parameter is set to &apos;I2C0&apos; or &apos;I2C1&apos; the component&apos;s pins should be connected to the corresponding port..
        /// </summary>
        internal static string DRCI2CBusPortError {
            get {
                return ResourceManager.GetString("DRCI2CBusPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Enable wakeup from Sleep Mode&quot; parameter is valid only for PSoC3 ES3, PSoC5 ES2, and later revisions..
        /// </summary>
        internal static string DRCRevisionError {
            get {
                return ResourceManager.GetString("DRCRevisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary slave and Secondary slave addresses cannot be equal..
        /// </summary>
        internal static string PrimarySecondaryEqualEP {
            get {
                return ResourceManager.GetString("PrimarySecondaryEqualEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary slave address must be between 0 and 127..
        /// </summary>
        internal static string PrimarySlaveAddressEP {
            get {
                return ResourceManager.GetString("PrimarySlaveAddressEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary slave address must be between 0 and 127..
        /// </summary>
        internal static string SecondarySlaveAddressEP {
            get {
                return ResourceManager.GetString("SecondarySlaveAddressEP", resourceCulture);
            }
        }
    }
}
