//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicLCDCtrl_v1_60 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphicLCDCtrl_v1_60.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string BasicTabCaption {
            get {
                return ResourceManager.GetString("BasicTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabCaption {
            get {
                return ResourceManager.GetString("BuiltInTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Active Region value must be between 4 and 1024..
        /// </summary>
        internal static string EPHActiveRegionMsg1 {
            get {
                return ResourceManager.GetString("EPHActiveRegionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Active Region must be a multiple of 4..
        /// </summary>
        internal static string EPHActiveRegionMsg2 {
            get {
                return ResourceManager.GetString("EPHActiveRegionMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Back Porch value must be set between 6 and 256..
        /// </summary>
        internal static string EPHBackPorchMsg {
            get {
                return ResourceManager.GetString("EPHBackPorchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Front Porch value must be between 1 and 256..
        /// </summary>
        internal static string EPHFrontPorchMsg {
            get {
                return ResourceManager.GetString("EPHFrontPorchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Sync Width value must be between 1 and 256..
        /// </summary>
        internal static string EPHSyncWidthMsg {
            get {
                return ResourceManager.GetString("EPHSyncWidthMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Active Region value must be between 4 and 1024..
        /// </summary>
        internal static string EPVActiveRegionMsg1 {
            get {
                return ResourceManager.GetString("EPVActiveRegionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Active Region must be a multiple of 4..
        /// </summary>
        internal static string EPVActiveRegionMsg2 {
            get {
                return ResourceManager.GetString("EPVActiveRegionMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Back Porch value must be set between 1 and 256..
        /// </summary>
        internal static string EPVBackPorchMsg {
            get {
                return ResourceManager.GetString("EPVBackPorchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Front Porch value must be between 1 and 256..
        /// </summary>
        internal static string EPVFrontPorchMsg {
            get {
                return ResourceManager.GetString("EPVFrontPorchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sync Width value must be between 1 and 256..
        /// </summary>
        internal static string EPVSyncWidthMsg {
            get {
                return ResourceManager.GetString("EPVSyncWidthMsg", resourceCulture);
            }
        }
    }
}
