/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <adc.h>
#include <amux.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <lcd.h>
#include <ledhb_aliases.h>
#include <ledhb.h>
#include <led_aliases.h>
#include <led.h>
#include <i2c.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <adc_theACLK.h>
#include <adc_Ext_CP_Clk.h>
#include <lcd_LCDPort_aliases.h>
#include <lcd_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
