//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticSegLCD_v1_50.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticSegLCD_v1_50.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all changes?.
        /// </summary>
        internal static string CHARS_RESET_MSG {
            get {
                return ResourceManager.GetString("CHARS_RESET_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name could not be an empty string..
        /// </summary>
        internal static string EMPTY_NAME_MSG {
            get {
                return ResourceManager.GetString("EMPTY_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_MSG_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of helpers is {0:G}. Helper could not be added..
        /// </summary>
        internal static string HELPERS_LIMIT_MSG {
            get {
                return ResourceManager.GetString("HELPERS_LIMIT_MSG", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap im_add {
            get {
                object obj = ResourceManager.GetObject("im_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_arrowleft {
            get {
                object obj = ResourceManager.GetObject("im_arrowleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_arrowright {
            get {
                object obj = ResourceManager.GetObject("im_arrowright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_delete {
            get {
                object obj = ResourceManager.GetObject("im_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION_MSG_TITLE {
            get {
                return ResourceManager.GetString("INFORMATION_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough segment and common lines to manage helpers
        ///Helper could not be added..
        /// </summary>
        internal static string NOT_ENOUGH_SEG_COM_MSG {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_SEG_COM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is not unique. Please, enter another name..
        /// </summary>
        internal static string NOT_UNIQUE_NAME_MSG {
            get {
                return ResourceManager.GetString("NOT_UNIQUE_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file..
        /// </summary>
        internal static string OPEN_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("OPEN_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Helpers parameter..
        /// </summary>
        internal static string PARAMETERS_LOADING_ERROR_MSG {
            get {
                return ResourceManager.GetString("PARAMETERS_LOADING_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error during printing occured..
        /// </summary>
        internal static string PRINT_ERROR_MSG {
            get {
                return ResourceManager.GetString("PRINT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QUESTION_MSG_TITLE {
            get {
                return ResourceManager.GetString("QUESTION_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during XML serialization occured..
        /// </summary>
        internal static string SAVE_TEMPLATE_ERROR_MSG {
            get {
                return ResourceManager.GetString("SAVE_TEMPLATE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreasing the number of segment lines will cause the loss
        ///of pixel mapping information for removed segment lines.
        /// </summary>
        internal static string SEG_LINES_DECREASE_MSG {
            get {
                return ResourceManager.GetString("SEG_LINES_DECREASE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Configuration.
        /// </summary>
        internal static string TAB_BASIC_NAME {
            get {
                return ResourceManager.GetString("TAB_BASIC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string TAB_BUILTIN_NAME {
            get {
                return ResourceManager.GetString("TAB_BUILTIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Helpers.
        /// </summary>
        internal static string TAB_HELPERS_NAME {
            get {
                return ResourceManager.GetString("TAB_HELPERS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To assign a pixel, drag it onto the Pixel Mapping Table below.
        /// </summary>
        internal static string TIP_PIXELS_DRAG {
            get {
                return ResourceManager.GetString("TIP_PIXELS_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WARNING_MSG_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the file..
        /// </summary>
        internal static string WRITE_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("WRITE_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} has wrong format..
        /// </summary>
        internal static string WRONG_FORMAT_PARAM_MSG {
            get {
                return ResourceManager.GetString("WRONG_FORMAT_PARAM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain only letters, digits and &apos;_&apos; char..
        /// </summary>
        internal static string WRONG_SYMBOL_MSG {
            get {
                return ResourceManager.GetString("WRONG_SYMBOL_MSG", resourceCulture);
            }
        }
    }
}
