

package org.elkhorncreek;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;


import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import org.jfree.data.jdbc.JDBCXYDataset;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.chart.*;


/**
 * A basic servlet that returns a PNG image file generated by JFreeChart.
 * This class is described in the JFreeChart Developer Guide in the
 * "Servlets" chapter.
 */
public class CreekInfo extends HttpServlet {

	/**
	 * Creates a new demo.
	 */


	public CreekInfo() {
		// nothing required
	}

	/**
	 * Processes a GET request.
	 *
	 * @param request  the request.
	 * @param response  the response.
	 *
	 * @throws ServletException if there is a servlet related problem.
	 * @throws IOException if there is an I/O problem.
	 */
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		OutputStream out = response.getOutputStream();


		String url = "jdbc:mysql://192.168.15.80/d1";
		Connection con;

		try {
			Class.forName("com.mysql.jdbc.Driver");
		}
		catch (ClassNotFoundException e) {
			System.err.print("ClassNotFoundException: ");
			System.err.println(e.getMessage());
		}

		/*
		try {
			con = DriverManager.getConnection(url, "creek", "creek");

			data = new JDBCXYDataset(con);

			String sql = "SELECT ts,depth,60min FROM ddata order by ts desc limit 1;";
			
			
			response.setContentType("text/html");
			
			con.close();
		}

	
		catch (Exception e) {
			System.err.print("Exception: ");
			System.err.println(e.getMessage());
		}




				response.setContentType("text/csv");
				int i = data.getItemCount(0);
				OutputStreamWriter ow = new OutputStreamWriter(out);
				ow.write("Timestamp,ft\n");
				for(int j=0;j<i;j++)
				{
					ow.write(data.getX(0,j) + "," + data.getY(0,j) + "\n");
				}
			}

		}
		catch (Exception e) {
			System.err.println(e.toString());
		}
		
		finally {


			out.close();
		}
		*/

	}

}
