//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoltageFaultDetector_v2_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoltageFaultDetector_v2_0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltages table contains wrong data.
        /// </summary>
        public static string DataGridError {
            get {
                return ResourceManager.GetString("DataGridError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference must be selected for current device.
        /// </summary>
        public static string DRCExtRefError {
            get {
                return ResourceManager.GetString("DRCExtRefError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltages table contains empty cells.
        /// </summary>
        public static string DrcNullValuesError {
            get {
                return ResourceManager.GetString("DrcNullValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoltageFaultDetector_v2_0 is not supported on this device. Use the device selector to change the selected device..
        /// </summary>
        public static string DrcPSoC5 {
            get {
                return ResourceManager.GetString("DrcPSoC5", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        public static string FileDialogExt {
            get {
                return ResourceManager.GetString("FileDialogExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        public static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read file {0}..
        /// </summary>
        public static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to file {0}..
        /// </summary>
        public static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Table.
        /// </summary>
        public static string FilterDialogExportTitle {
            get {
                return ResourceManager.GetString("FilterDialogExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Table.
        /// </summary>
        public static string FilterDialogImportTitle {
            get {
                return ResourceManager.GetString("FilterDialogImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTabDisplayName {
            get {
                return ResourceManager.GetString("GeneralTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitch filter length must be between {0} and {1}..
        /// </summary>
        public static string GFLengthError {
            get {
                return ResourceManager.GetString("GFLengthError", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data in the grid will be lost after import. Would you like to continue?.
        /// </summary>
        public static string ImportConfirmation {
            get {
                return ResourceManager.GetString("ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input voltage scaling factor must be between {0} and {1}..
        /// </summary>
        public static string InputScalingFactorError {
            get {
                return ResourceManager.GetString("InputScalingFactorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert data into table. Data format is not valid..
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data in clipboard does match columns in the table..
        /// </summary>
        public static string InvalidDataInClipboard {
            get {
                return ResourceManager.GetString("InvalidDataInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgErrorTitle {
            get {
                return ResourceManager.GetString("MsgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgWarningTitle {
            get {
                return ResourceManager.GetString("MsgWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal output voltage value must be between {0} V and {1} V..
        /// </summary>
        public static string NominalOutputVoltageError {
            get {
                return ResourceManager.GetString("NominalOutputVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of voltages must be between {0} and {1}..
        /// </summary>
        public static string NumVoltagesError {
            get {
                return ResourceManager.GetString("NumVoltagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV fault threshold value multiplied by scale must be lower or equal than DAC range when External reference is false..
        /// </summary>
        public static string OvFaultMultScaleSanityCheck {
            get {
                return ResourceManager.GetString("OvFaultMultScaleSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV fault threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string OvFaultThresholdError {
            get {
                return ResourceManager.GetString("OvFaultThresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold must be lower or equal than OV  fault threshold..
        /// </summary>
        public static string OvUvVoltagesCompareSanityCheck {
            get {
                return ResourceManager.GetString("OvUvVoltagesCompareSanityCheck", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have incorrect values. You must redefine them..
        /// </summary>
        public static string SettingsIncorrectValues {
            get {
                return ResourceManager.GetString("SettingsIncorrectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold value multiplied by scale must be greater or equal 50 mV..
        /// </summary>
        public static string UvFaultMultScaleSanityCheck {
            get {
                return ResourceManager.GetString("UvFaultMultScaleSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string UvFaultThresholdError {
            get {
                return ResourceManager.GetString("UvFaultThresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal voltage should be greater or equal than UV fault threshold and lower or equal than OV  fault threshold..
        /// </summary>
        public static string VoltagesCompareSanityCheck {
            get {
                return ResourceManager.GetString("VoltagesCompareSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltages.
        /// </summary>
        public static string VoltagesTabDisplayName {
            get {
                return ResourceManager.GetString("VoltagesTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input clock frequency should not exceed {0} MHz when DAC range is {1}.
        /// </summary>
        public static string WarningMaxClockValue {
            get {
                return ResourceManager.GetString("WarningMaxClockValue", resourceCulture);
            }
        }
    }
}
