/*******************************************************************************
* File Name: `$INSTANCE_NAME`.c
* Version `$CY_MAJOR_VERSION`.`$CY_MINOR_VERSION`
*
* Description:
*  The Vector CAN Component is a third Party Industry Standard CAN driver 
*  supplier.
*
* Note: 
*  None
*
********************************************************************************
* Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "`$INSTANCE_NAME`.h"

uint8 `$INSTANCE_NAME`_initVar = 0u;


/*******************************************************************************
* FUNCTION NAME:  `$INSTANCE_NAME`_Init
********************************************************************************
*
* Summary:
*  Initializes the Vector CAN component based on settings in the component 
*  customizer. Sets up the CAN interrupt with the interrupt service routine 
*  CanIsr_0() generated by the Vector CAN configuration tool.
*
* Parameters:
*  None.
*
* Return:
*  Indication whether register is written and verified.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_Init(void) `=ReentrantKeil($INSTANCE_NAME . "_Init")`
{    
    uint8 result = CYRET_SUCCESS;
    
    #if (`$INSTANCE_NAME`_ENABLE_INTERRUPTS)
    
        uint8 enableInterrupts = 0u;
    
        /* Disable Interrupt. */
        CyIntDisable(`$INSTANCE_NAME`_ISR_NUMBER);

        /* Set the ISR to point to the CanIsr_0 Interrupt. */
        CyIntSetVector(`$INSTANCE_NAME`_ISR_NUMBER, CanIsr_0);

        /* Set the priority. */
        CyIntSetPriority(`$INSTANCE_NAME`_ISR_NUMBER, `$INSTANCE_NAME`_ISR_PRIORITY);                     
    
        enableInterrupts = CyEnterCriticalSection();
        
        /* Enable Vector CAN block in Active mode */
        `$INSTANCE_NAME`_PM_ACT_CFG_REG |= `$INSTANCE_NAME`_ACT_PWR_EN;

        /* Enable Vector CAN block in Alternate Active (Standby) mode */
        `$INSTANCE_NAME`_PM_STBY_CFG_REG |= `$INSTANCE_NAME`_STBY_PWR_EN;
            
        CyExitCriticalSection(enableInterrupts);
                      
        result = `$INSTANCE_NAME`_GlobalIntEnable();
        
    #endif /* `$INSTANCE_NAME`_ENABLE_INTERRUPTS */
    
    return(result);
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_Enable
********************************************************************************
*
* Summary:   
*  This function enable the Vector CAN component. 
*
* Parameters:  
*  None.
*
* Return: 
*  Indication whether register is written and verified.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_Enable(void) `=ReentrantKeil($INSTANCE_NAME . "_Enable")`
{
    uint8 result = `$INSTANCE_NAME`_FAIL;
    uint8 enableInterrupts = 0u;
    
    enableInterrupts = CyEnterCriticalSection();
    
    /* Enable Vector CAN block in Active mode */
    `$INSTANCE_NAME`_PM_ACT_CFG_REG |= `$INSTANCE_NAME`_ACT_PWR_EN;

    /* Enable Vector CAN block in Alternate Active (Standby) mode */
    `$INSTANCE_NAME`_PM_STBY_CFG_REG |= `$INSTANCE_NAME`_STBY_PWR_EN;
    
    CyExitCriticalSection(enableInterrupts);
    
    #if (`$INSTANCE_NAME`_ENABLE_INTERRUPTS)
    
        /* Enable isr */
        CyIntEnable(`$INSTANCE_NAME`_ISR_NUMBER);   
        
    #endif /* `$INSTANCE_NAME`_ENABLE_INTERRUPTS */
    
    /* Sets the Vector CAN controller to run mode */
    CY_SET_REG32(`$INSTANCE_NAME`_CMD_PTR, (CY_GET_REG32(`$INSTANCE_NAME`_CMD_PTR) | `$INSTANCE_NAME`_MODE_MASK));
    
    /* Verify that bit is set */
    if (0u != (CY_GET_REG32(`$INSTANCE_NAME`_CMD_PTR) & `$INSTANCE_NAME`_MODE_MASK))
    {
        result = CYRET_SUCCESS;
    }
    
    return(result);
}


/*******************************************************************************
* FUNCTION NAME:   `$INSTANCE_NAME`_Start
********************************************************************************
*
* Summary:
*  Initializes and enables the Vector CAN component using the CAN_Init() and 
*  CAN_Enable() functions.
*
* Parameters:
*  None. 
*
* Return:
*  Indication whether register is written and verified.  
*
* Global variables:
*  `$INSTANCE_NAME`_initVar - used to check initial configuration, modified on
*  first function call.
*
* Reentrant:
*  No.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_Start(void)
{
    uint8 result = `$INSTANCE_NAME`_FAIL;
    
    if (`$INSTANCE_NAME`_initVar == 0u)
    {
        result = `$INSTANCE_NAME`_Init();
        `$INSTANCE_NAME`_initVar = 1u;
    }
    
    if (result == CYRET_SUCCESS)
    {
        result = `$INSTANCE_NAME`_Enable();
    }

    return(result);
}


/*******************************************************************************
* FUNCTION NAME:   `$INSTANCE_NAME`_Stop
********************************************************************************
*
* Summary:
*  Disables the Vector CAN component.
*
* Parameters:
*  None.
*
* Return:
*  Indication whether register is written and verified.
*
* Side Effects:
*  Disable power to the Vector CAN Core.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_Stop(void) `=ReentrantKeil($INSTANCE_NAME . "_Stop")`
{
    uint8 result = `$INSTANCE_NAME`_FAIL;
    uint8 enableInterrupts = 0u;        
    
    /* Sets the Vector CAN controller to stop mode */
    CY_SET_REG32(`$INSTANCE_NAME`_CMD_PTR, (CY_GET_REG32(`$INSTANCE_NAME`_CMD_PTR) & (~`$INSTANCE_NAME`_MODE_MASK)));

    /* Verify that bit is cleared */
    if ((CY_GET_REG32(`$INSTANCE_NAME`_CMD_PTR) & `$INSTANCE_NAME`_MODE_MASK) == 0u)
    {
        result = CYRET_SUCCESS;
    }
    
    #if (`$INSTANCE_NAME`_ENABLE_INTERRUPTS)
    
        /* Disable interrupt */
        CyIntDisable(`$INSTANCE_NAME`_ISR_NUMBER);   
        
    #endif /* `$INSTANCE_NAME`_ENABLE_INTERRUPTS */
    
    
    enableInterrupts = CyEnterCriticalSection(); 

    /* Disable Vector CAN block in Active mode */
    `$INSTANCE_NAME`_PM_ACT_CFG_REG &= ~`$INSTANCE_NAME`_ACT_PWR_EN;

    /* Disable Vector CAN block in Alternate Active (Standby) mode template */
    `$INSTANCE_NAME`_PM_STBY_CFG_REG &= ~`$INSTANCE_NAME`_STBY_PWR_EN;
    
    CyExitCriticalSection(enableInterrupts);

    return(result);
}


/*******************************************************************************
* FUNCTION NAME:   `$INSTANCE_NAME`_GlobalIntEnable
********************************************************************************
*
* Summary:
*  This function enables Global Interrupts from Vector CAN Core.
*
* Parameters:
*  None.
*
* Return:
*  Indication whether register is written and verified.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_GlobalIntEnable(void) `=ReentrantKeil($INSTANCE_NAME . "_GlobalIntEnable")`
{
    uint8 result = `$INSTANCE_NAME`_FAIL;

    CY_SET_REG32(`$INSTANCE_NAME`_INT_EN_PTR, (CY_GET_REG32(`$INSTANCE_NAME`_INT_EN_PTR) | 
                 `$INSTANCE_NAME`_GLOBAL_INT_MASK));
    
    /* Verify that bit is set */
    if (0u != (CY_GET_REG32(`$INSTANCE_NAME`_INT_EN_PTR) & `$INSTANCE_NAME`_GLOBAL_INT_MASK))
    {
        result = CYRET_SUCCESS;
    }

    return(result);
}


/*******************************************************************************
* FUNCTION NAME:   `$INSTANCE_NAME`_GlobalIntDisable
********************************************************************************
*
* Summary:
*  This function disables Global Interrupts from Vector CAN Core.
*
* Parameters:
*  None.
*
* Return:
*  Indication whether register is written and verified.
*
*******************************************************************************/
uint8 `$INSTANCE_NAME`_GlobalIntDisable(void) `=ReentrantKeil($INSTANCE_NAME . "_GlobalIntDisable")`
{
    uint8 result = `$INSTANCE_NAME`_FAIL;

    CY_SET_REG32(`$INSTANCE_NAME`_INT_EN_PTR, (CY_GET_REG32(`$INSTANCE_NAME`_INT_EN_PTR) & 
                (~`$INSTANCE_NAME`_GLOBAL_INT_MASK)));

    /* Verify that bit is cleared */
    if ((CY_GET_REG32(`$INSTANCE_NAME`_INT_EN_PTR) & `$INSTANCE_NAME`_GLOBAL_INT_MASK) == 0u)
    {
        result = CYRET_SUCCESS;
    }

    return(result);
}


/* [] END OF FILE */
