/*******************************************************************************
* File Name: cyPm.h
* Version `$CY_MAJOR_VERSION`.`$CY_MINOR_VERSION`
*
*  Description:
*   Provides the function definitions for the power management API.
*
*  Note:
*   Documentation of the API's in this file is located in the
*   System Reference Guide provided with PSoC Creator.
*
********************************************************************************
* Copyright 2011-2012, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#if !defined(CY_BOOT_CYPM_H)
#define CY_BOOT_CYPM_H

#include "cytypes.h"


/***************************************
*        Function Prototypes
***************************************/
void CySysPmSleep(void);
void CySysPmDeepSleep(void);
void CySysPmHibernate(void);


/***************************************
*       Macro definition
***************************************/

/*******************************************************************************
* The ARM compilers has __wfi() instristic that inserts a WFI instruction into
* the instruction stream generated by the compiler. The GCC compiler has to
* execute assembly language instruction.
*******************************************************************************/
#if defined(__ARMCC_VERSION)    /* Instristic for Keil compilers */
    #define CY_PM_WFI       __wfi()
#else   /* ASM for GCC */
    #define CY_PM_WFI       asm volatile ("WFI \n")
#endif /* End of (__ARMCC_VERSION) */


/***************************************
*              Registers
***************************************/

/* Power Mode Control */
#define CY_PM_PWR_CONTROL_REG               (*(reg32 *) CYREG_PWR_CONTROL)
#define CY_PM_PWR_CONTROL_PTR               ( (reg32 *) CYREG_PWR_CONTROL)

/* CM0 System Control Register */
#define CY_PM_CM0_SCR_REG                   (*(reg32 *) CYREG_CM0_SCR)
#define CY_PM_CM0_SCR_PTR                   ( (reg32 *) CYREG_CM0_SCR)


/***************************************
*       Register Constants
***************************************/

/* Power Mode Control Constants */
#define CY_PM_PWR_CONTROL_HIBERNATE         (0x80000000u)

/* CM0 System Control Register Constants */
#define CY_PM_CM0_SCR_SLEEPDEEP             (0x00000004u)

#endif  /* CY_BOOT_CYPM_H */


/* [] END OF FILE */
