//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrimMargin_v1_10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrimMargin_v1_10.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string ControlVoltageError {
            get {
                return ResourceManager.GetString("ControlVoltageError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tab table contains wrong data..
        /// </summary>
        internal static string DataGridError {
            get {
                return ResourceManager.GetString("DataGridError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} table contains empty cells..
        /// </summary>
        internal static string DrcNullValuesError {
            get {
                return ResourceManager.GetString("DrcNullValuesError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        internal static string ExportAllTitle {
            get {
                return ResourceManager.GetString("ExportAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to File.
        /// </summary>
        internal static string ExportDialogHeader {
            get {
                return ResourceManager.GetString("ExportDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this name already exists. Do you want to replace it?.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read file {0}..
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to file {0}..
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitch filter length must be between {0} and {1}..
        /// </summary>
        internal static string GFLengthError {
            get {
                return ResourceManager.GetString("GFLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power converter circuit parameters.
        /// </summary>
        internal static string HeaderPowerConv {
            get {
                return ResourceManager.GetString("HeaderPowerConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM parameters.
        /// </summary>
        internal static string HeaderPWMParams {
            get {
                return ResourceManager.GetString("HeaderPWMParams", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import All.
        /// </summary>
        internal static string ImportAllTitle {
            get {
                return ResourceManager.GetString("ImportAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data in the grid will be lost after import. Would you like to continue?.
        /// </summary>
        internal static string ImportConfirmation {
            get {
                return ResourceManager.GetString("ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        internal static string ImportDialogHeader {
            get {
                return ResourceManager.GetString("ImportDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input voltage scaling factor must be between {0} and {1}..
        /// </summary>
        internal static string InputScalingFactorError {
            get {
                return ResourceManager.GetString("InputScalingFactorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert data into table. Data format is not valid..
        /// </summary>
        internal static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data in clipboard does match columns in the table..
        /// </summary>
        internal static string InvalidDataInClipboard {
            get {
                return ResourceManager.GetString("InvalidDataInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin high percentage value must be between {0} and {1}..
        /// </summary>
        internal static string MarginHighPercentageError {
            get {
                return ResourceManager.GetString("MarginHighPercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin high voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string MarginHighVoltageError {
            get {
                return ResourceManager.GetString("MarginHighVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin high voltage value must be less than or equal to maximum output voltage..
        /// </summary>
        internal static string MarginHighVoltageSanityCheck {
            get {
                return ResourceManager.GetString("MarginHighVoltageSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin low percentage value must be between {0} and {1}..
        /// </summary>
        internal static string MarginLowPercentageError {
            get {
                return ResourceManager.GetString("MarginLowPercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin low voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string MarginLowVoltageError {
            get {
                return ResourceManager.GetString("MarginLowVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin low voltage value must be less than or equal to nominal output voltage..
        /// </summary>
        internal static string MarginLowVoltageSanityCheck {
            get {
                return ResourceManager.GetString("MarginLowVoltageSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum desired voltage ripple value must be between {0} mV and {1} mV..
        /// </summary>
        internal static string MaxRippleError {
            get {
                return ResourceManager.GetString("MaxRippleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum output voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string MaxVoltageError {
            get {
                return ResourceManager.GetString("MaxVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum output voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string MinVoltageError {
            get {
                return ResourceManager.GetString("MinVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum output voltage value must be less than or equal to margin Low voltage..
        /// </summary>
        internal static string MinVoltageSanityCheck {
            get {
                return ResourceManager.GetString("MinVoltageSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal output voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string NominalOutputVoltageError {
            get {
                return ResourceManager.GetString("NominalOutputVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal output voltage value must be less than or equal to margin high voltage..
        /// </summary>
        internal static string NominalOutputVoltageSanityCheck {
            get {
                return ResourceManager.GetString("NominalOutputVoltageSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Resolution must be between {0} and {1}..
        /// </summary>
        internal static string NumPWMResolutionError {
            get {
                return ResourceManager.GetString("NumPWMResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of voltages must be between {0} and {1}..
        /// </summary>
        internal static string NumVoltagesError {
            get {
                return ResourceManager.GetString("NumVoltagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of converts should be in the range {0}-{1}, when {2} to {3}-bit PWM resolution selected..
        /// </summary>
        internal static string NumVoltagesWithPWMResolutionError {
            get {
                return ResourceManager.GetString("NumVoltagesWithPWMResolutionError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1 external scaling resistor value must be between {0} kOhm and {1} kOhm..
        /// </summary>
        internal static string R1ResistorError {
            get {
                return ResourceManager.GetString("R1ResistorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2 external scaling resistor value must be between {0} kOhm and {1} kOhm..
        /// </summary>
        internal static string R2ResistorError {
            get {
                return ResourceManager.GetString("R2ResistorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R3 external scaling resistor value must be between {0} kOhm and {1} kOhm..
        /// </summary>
        internal static string R3ResistorError {
            get {
                return ResourceManager.GetString("R3ResistorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R4 external scaling resistor value must be between {0} kOhm and {1} kOhm..
        /// </summary>
        internal static string R4ResistorError {
            get {
                return ResourceManager.GetString("R4ResistorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have incorrect values. You must redefine them..
        /// </summary>
        internal static string SettingsIncorrectValues {
            get {
                return ResourceManager.GetString("SettingsIncorrectValues", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap trim_margin {
            get {
                object obj = ResourceManager.GetObject("trim_margin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDDIO voltage value must be between {0} V and {1} V..
        /// </summary>
        internal static string VDDIOVoltageError {
            get {
                return ResourceManager.GetString("VDDIOVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal voltage should be greater or equal than UV fault threshold and lower or equal than OV  fault threshold..
        /// </summary>
        internal static string VoltagesCompareSanityCheck {
            get {
                return ResourceManager.GetString("VoltagesCompareSanityCheck", resourceCulture);
            }
        }
    }
}
