#!/bin/sh
cd ~pi/getCreek
sudo i2cget -y 1 8 0
sudo i2cget -y 1 8 1
sudo i2cget -y 1 8 2
sudo i2cget -y 1 8 3
sudo java -cp build/jar/getCreek.jar:lib/pi4j-core-0.0.3-SNAPSHOT.jar:lib/mysql-connector-java-5.1.6-bin.jar getCreek print 
