//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapSense_v1_30.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapSense_v1_30.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap cmddemote {
            get {
                object obj = ResourceManager.GetObject("cmddemote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cmdpromote {
            get {
                object obj = ResourceManager.GetObject("cmdpromote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lidacsinking {
            get {
                object obj = ResourceManager.GetObject("lidacsinking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lidacsinkingprs {
            get {
                object obj = ResourceManager.GetObject("lidacsinkingprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lidacsourcing {
            get {
                object obj = ResourceManager.GetObject("lidacsourcing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lidacsourcingprs {
            get {
                object obj = ResourceManager.GetObject("lidacsourcingprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalerhw_csa {
            get {
                object obj = ResourceManager.GetObject("lprescalerhw_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalerhw_csd {
            get {
                object obj = ResourceManager.GetObject("lprescalerhw_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalernone_csa {
            get {
                object obj = ResourceManager.GetObject("lprescalernone_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalernone_csd {
            get {
                object obj = ResourceManager.GetObject("lprescalernone_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalerudb_csa {
            get {
                object obj = ResourceManager.GetObject("lprescalerudb_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lprescalerudb_csd {
            get {
                object obj = ResourceManager.GetObject("lprescalerudb_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lrb {
            get {
                object obj = ResourceManager.GetObject("lrb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lrbprs {
            get {
                object obj = ResourceManager.GetObject("lrbprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ridacsinking {
            get {
                object obj = ResourceManager.GetObject("ridacsinking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ridacsinkingprs {
            get {
                object obj = ResourceManager.GetObject("ridacsinkingprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ridacsourcing {
            get {
                object obj = ResourceManager.GetObject("ridacsourcing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ridacsourcingprs {
            get {
                object obj = ResourceManager.GetObject("ridacsourcingprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalerhw_csa {
            get {
                object obj = ResourceManager.GetObject("rprescalerhw_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalerhw_csd {
            get {
                object obj = ResourceManager.GetObject("rprescalerhw_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalernone_csa {
            get {
                object obj = ResourceManager.GetObject("rprescalernone_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalernone_csd {
            get {
                object obj = ResourceManager.GetObject("rprescalernone_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalerudb_csa {
            get {
                object obj = ResourceManager.GetObject("rprescalerudb_csa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rprescalerudb_csd {
            get {
                object obj = ResourceManager.GetObject("rprescalerudb_csd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rrb {
            get {
                object obj = ResourceManager.GetObject("rrb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rrbprs {
            get {
                object obj = ResourceManager.GetObject("rrbprs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
