//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapSense_CSD_v2_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CyCsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CyCsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapSense_CSD_v2_0.CyCsResource", typeof(CyCsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedDisplayName {
            get {
                return ResourceManager.GetString("AdvancedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Tuning mode can&apos;t work when the value of Current Source is &quot;External Resistor&quot;. Please change configuration..
        /// </summary>
        public static string AutoTuningLimitation {
            get {
                return ResourceManager.GetString("AutoTuningLimitation", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string BuiltInDisplayName {
            get {
                return ResourceManager.GetString("BuiltInDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name [{0}].
        /// </summary>
        public static string ChangeNameHeader {
            get {
                return ResourceManager.GetString("ChangeNameHeader", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap clk {
            get {
                object obj = ResourceManager.GetObject("clk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_ff {
            get {
                object obj = ResourceManager.GetObject("clk_ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_ff_prs16 {
            get {
                object obj = ResourceManager.GetObject("clk_ff_prs16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_ff_prs16_4 {
            get {
                object obj = ResourceManager.GetObject("clk_ff_prs16_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_ff_prs8 {
            get {
                object obj = ResourceManager.GetObject("clk_ff_prs8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_prs16 {
            get {
                object obj = ResourceManager.GetObject("clk_prs16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_prs16_4 {
            get {
                object obj = ResourceManager.GetObject("clk_prs16_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_prs8 {
            get {
                object obj = ResourceManager.GetObject("clk_prs8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_udb {
            get {
                object obj = ResourceManager.GetObject("clk_udb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_udb_prs16 {
            get {
                object obj = ResourceManager.GetObject("clk_udb_prs16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_udb_prs16_4 {
            get {
                object obj = ResourceManager.GetObject("clk_udb_prs16_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clk_udb_prs8 {
            get {
                object obj = ResourceManager.GetObject("clk_udb_prs8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScanSlot {0} is empty. Please assign sensors to it..
        /// </summary>
        public static string EmptyScanSlot {
            get {
                return ResourceManager.GetString("EmptyScanSlot", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap example_buttons {
            get {
                object obj = ResourceManager.GetObject("example_buttons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_generic {
            get {
                object obj = ResourceManager.GetObject("example_generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_matrixbutton {
            get {
                object obj = ResourceManager.GetObject("example_matrixbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_proximity {
            get {
                object obj = ResourceManager.GetObject("example_proximity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_slider {
            get {
                object obj = ResourceManager.GetObject("example_slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_sliderradial {
            get {
                object obj = ResourceManager.GetObject("example_sliderradial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap example_touchpad {
            get {
                object obj = ResourceManager.GetObject("example_touchpad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file..
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralDisplayName {
            get {
                return ResourceManager.GetString("GeneralDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FingerThreshold + Hysteresis can&apos;t be more than 255..
        /// </summary>
        public static string HA_FT_HY {
            get {
                return ResourceManager.GetString("HA_FT_HY", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap imadd {
            get {
                object obj = ResourceManager.GetObject("imadd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap imdelete {
            get {
                object obj = ResourceManager.GetObject("imdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap imimport {
            get {
                object obj = ResourceManager.GetObject("imimport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap imsave {
            get {
                object obj = ResourceManager.GetObject("imsave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string InvalidNameError {
            get {
                return ResourceManager.GetString("InvalidNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value.
        /// </summary>
        public static string MESSAGE_CLOCK_VALUE_UNKNOW {
            get {
                return ResourceManager.GetString("MESSAGE_CLOCK_VALUE_UNKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapSense CSD component supports clock frequency in range {0} and {1} MHz.
        ///Bus clock frequency exceed this limits..
        /// </summary>
        public static string MESSAGE_ERROR_BUS_CLK_FREQUNC_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_BUS_CLK_FREQUNC_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (SmartSense) tuning method supports only clock frequency 24MHz or
        ///Bus clock equal to 24MHz..
        /// </summary>
        public static string MESSAGE_ERROR_BUS_CLK_FREQUNC_LIMIT_AUTO {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_BUS_CLK_FREQUNC_LIMIT_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapSense CSD component supports clock frequency in range {0} and {1} MHz.
        ///External clock frequency exceeds this limits..
        /// </summary>
        public static string MESSAGE_ERROR_EXTERNAL_CLK_FREQUNC_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_EXTERNAL_CLK_FREQUNC_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF Timer does not support Scan Clock frequency that is equal or higher than Bus Clock.
        ///Please, choose Bus Clock as Scan Clock or select UDB Timer option on Advanced tab..
        /// </summary>
        public static string MESSAGE_ERROR_FF_BASE_LIMITATION {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_FF_BASE_LIMITATION", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap movedown {
            get {
                object obj = ResourceManager.GetObject("movedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap movetofirst {
            get {
                object obj = ResourceManager.GetObject("movetofirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap movetosecond {
            get {
                object obj = ResourceManager.GetObject("movetosecond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap moveup {
            get {
                object obj = ResourceManager.GetObject("moveup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rb_vref_ff {
            get {
                object obj = ResourceManager.GetObject("rb_vref_ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rb_vref_udb {
            get {
                object obj = ResourceManager.GetObject("rb_vref_udb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Order.
        /// </summary>
        public static string ScanOrderDisplayName {
            get {
                return ResourceManager.GetString("ScanOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Digital Resource Implementation&quot; with FF Timer option can&apos;t work with PSoC3 ES3 Silicon..
        /// </summary>
        public static string SiliconErrorDRI {
            get {
                return ResourceManager.GetString("SiliconErrorDRI", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap sinking_vref_ff {
            get {
                object obj = ResourceManager.GetObject("sinking_vref_ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sinking_vref_udb {
            get {
                object obj = ResourceManager.GetObject("sinking_vref_udb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sourcing_vdac_ff {
            get {
                object obj = ResourceManager.GetObject("sourcing_vdac_ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sourcing_vdac_udb {
            get {
                object obj = ResourceManager.GetObject("sourcing_vdac_udb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sourcing_vref_ff {
            get {
                object obj = ResourceManager.GetObject("sourcing_vref_ff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sourcing_vref_udb {
            get {
                object obj = ResourceManager.GetObject("sourcing_vref_udb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune Helper.
        /// </summary>
        public static string TuneHelperDisplayName {
            get {
                return ResourceManager.GetString("TuneHelperDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        public static string ValueLitation {
            get {
                return ResourceManager.GetString("ValueLitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets Config.
        /// </summary>
        public static string WidgetsDisplayName {
            get {
                return ResourceManager.GetString("WidgetsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML data is incorrect..
        /// </summary>
        public static string XmlDataIncorrect {
            get {
                return ResourceManager.GetString("XmlDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deserialization.
        /// </summary>
        public static string XmlDataIncorrectHeader {
            get {
                return ResourceManager.GetString("XmlDataIncorrectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapSense settings have incorrect values. Please redefine it for proper CapSense operations..
        /// </summary>
        public static string XmlError {
            get {
                return ResourceManager.GetString("XmlError", resourceCulture);
            }
        }
    }
}
