//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIF_v1_10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CyEMIFRresource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CyEMIFRresource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMIF_v1_10.CyEMIFRresource", typeof(CyEMIFRresource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabCaption {
            get {
                return ResourceManager.GetString("BuiltInTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus clock should be less than {0} MHz..
        /// </summary>
        internal static string DRCBusClkInvalidValue {
            get {
                return ResourceManager.GetString("DRCBusClkInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External memory speed must be in the range from {0} to {1}..
        /// </summary>
        internal static string ErrorExternalMemorySpeed {
            get {
                return ResourceManager.GetString("ErrorExternalMemorySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTabCaption {
            get {
                return ResourceManager.GetString("GeneralTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine number of bits in the address bus for external memory..
        /// </summary>
        internal static string LabelAddressWidth {
            get {
                return ResourceManager.GetString("LabelAddressWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine number of bits in the data bus for external memory..
        /// </summary>
        internal static string LabelDataWidth {
            get {
                return ResourceManager.GetString("LabelDataWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous External Memory Interface (3 external control 
        ///signals).
        /// </summary>
        internal static string LabelExtMemoryTypeAsync {
            get {
                return ResourceManager.GetString("LabelExtMemoryTypeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom mode used for all external memory types. Control 
        ///signals in this mode should be generated by additional 
        ///external logic (outside the component).
        /// </summary>
        internal static string LabelExtMemoryTypeCustom {
            get {
                return ResourceManager.GetString("LabelExtMemoryTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous External Memory Interface (6 external control 
        ///signals).
        /// </summary>
        internal static string LabelExtMemoryTypeSync {
            get {
                return ResourceManager.GetString("LabelExtMemoryTypeSync", resourceCulture);
            }
        }
    }
}
