//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegDisplay_v1_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SegDisplay_v1_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all changes?.
        /// </summary>
        internal static string CHARS_RESET_MSG {
            get {
                return ResourceManager.GetString("CHARS_RESET_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name could not be an empty string..
        /// </summary>
        internal static string EMPTY_NAME_MSG {
            get {
                return ResourceManager.GetString("EMPTY_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be between {0:G} and {1:G}..
        /// </summary>
        internal static string FORMAT_ERROR_MSG {
            get {
                return ResourceManager.GetString("FORMAT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be integer between {0:G} and {1:G}..
        /// </summary>
        internal static string FORMAT_INT_ERROR_MSG {
            get {
                return ResourceManager.GetString("FORMAT_INT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of helpers is {0:G}.\n Helper could not be added..
        /// </summary>
        internal static string HELPERS_LIMIT_MSG {
            get {
                return ResourceManager.GetString("HELPERS_LIMIT_MSG", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap imadd {
            get {
                object obj = ResourceManager.GetObject("imadd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imarrowleft {
            get {
                object obj = ResourceManager.GetObject("imarrowleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imarrowright {
            get {
                object obj = ResourceManager.GetObject("imarrowright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imdelete {
            get {
                object obj = ResourceManager.GetObject("imdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imimport {
            get {
                object obj = ResourceManager.GetObject("imimport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap immenu {
            get {
                object obj = ResourceManager.GetObject("immenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imrefresh {
            get {
                object obj = ResourceManager.GetObject("imrefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imsave {
            get {
                object obj = ResourceManager.GetObject("imsave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imundo {
            get {
                object obj = ResourceManager.GetObject("imundo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the alphabet..
        /// </summary>
        internal static string LOAD_TEMPLATE_ERROR_MSG {
            get {
                return ResourceManager.GetString("LOAD_TEMPLATE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough segment and common lines to manage helpers.
        ///Helper could not be added..
        /// </summary>
        internal static string NOT_ENOUGH_SEG_COM_MSG {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_SEG_COM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is not unique. Please, enter another name..
        /// </summary>
        internal static string NOT_UNIQUE_NAME_MSG {
            get {
                return ResourceManager.GetString("NOT_UNIQUE_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreasing the number of common or segment lines will cause
        ///the loss of pixel mapping information for removed lines .
        /// </summary>
        internal static string NUMLINES_DECREASE_MSG {
            get {
                return ResourceManager.GetString("NUMLINES_DECREASE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file..
        /// </summary>
        internal static string OPEN_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("OPEN_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Configuration.
        /// </summary>
        internal static string PAGE_TITLE_BASIC {
            get {
                return ResourceManager.GetString("PAGE_TITLE_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string PAGE_TITLE_BUILTIN {
            get {
                return ResourceManager.GetString("PAGE_TITLE_BUILTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Characters.
        /// </summary>
        internal static string PAGE_TITLE_CUSTOMCHARS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CUSTOMCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Helpers.
        /// </summary>
        internal static string PAGE_TITLE_HELPERS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_HELPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Power Settings.
        /// </summary>
        internal static string PAGE_TITLE_POWERSETTINGS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_POWERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in commiting parameter..
        /// </summary>
        internal static string PARAMETERS_COMMIT_ERROR_MSG {
            get {
                return ResourceManager.GetString("PARAMETERS_COMMIT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Helpers parameter..
        /// </summary>
        internal static string PARAMETERS_LOADING_ERROR_MSG {
            get {
                return ResourceManager.GetString("PARAMETERS_LOADING_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error during printing occured..
        /// </summary>
        internal static string PRINT_ERROR_MSG {
            get {
                return ResourceManager.GetString("PRINT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, remove helper functions first..
        /// </summary>
        internal static string REMOVE_HELPERS_MSG {
            get {
                return ResourceManager.GetString("REMOVE_HELPERS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegDisplay_v1_0 does not support PSoC3 devices newer than the ES2 revision. Please use the device selector to change the selected device revision or use a newer version of the SegLCD component..
        /// </summary>
        internal static string REVISION_ERROR_MSG {
            get {
                return ResourceManager.GetString("REVISION_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during XML serialization occured..
        /// </summary>
        internal static string SAVE_TEMPLATE_ERROR_MSG {
            get {
                return ResourceManager.GetString("SAVE_TEMPLATE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To assign a pixel, drag it onto the Pixel Mapping Table below.
        /// </summary>
        internal static string TIP_PIXELS_DRAG {
            get {
                return ResourceManager.GetString("TIP_PIXELS_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to use default chars list?.
        /// </summary>
        internal static string USE_DEFAULT_CHAR_LIST_MSG {
            get {
                return ResourceManager.GetString("USE_DEFAULT_CHAR_LIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the file..
        /// </summary>
        internal static string WRITE_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("WRITE_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} has wrong format..
        /// </summary>
        internal static string WRONG_FORMAT_PARAM_MSG {
            get {
                return ResourceManager.GetString("WRONG_FORMAT_PARAM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain only letters, digits and &apos;_&apos; symbol..
        /// </summary>
        internal static string WRONG_SYMBOL_MSG {
            get {
                return ResourceManager.GetString("WRONG_SYMBOL_MSG", resourceCulture);
            }
        }
    }
}
